version : "2"
services:
        master:
                image: mysql
                environment:
                        MYSQL_ROOT_PASSWORD: admin
                ports:
                        - "3307:3306"
                volumes:
                        - "./mysql-m.cnf:/etc/mysql/mysql.cnf"
                command:
                        - "--character-set-server=utf8mb4"
                        - "--collation-server=utf8mb4_unicode_ci"
        slave:
                image: mysql
                environment:
                        MYSQL_ROOT_PASSWORD: admin
                links:
                        - "master:master"
                depends_on:
                        - master
                ports:
                        - "3308:3306"
                volumes:
                        - "./mysql-s.cnf:/etc/mysql/mysql.cnf"
                command:
                        - "--character-set-server=utf8mb4"
                        - "--collation-server=utf8mb4_unicode_ci"
        php:
                image: tu6ge/php-mysql
                links:
                        - "master:mysql-m"
                        - "slave:mysql-s"
                depends_on:
                        - master
                        - slave 
                volumes:
                        - "./php/mysql.php:/var/www/html/mysql.php" 
