version : "2"
services:
        master:
                image: mysql
                environment:
                        MYSQL_ROOT_PASSWORD: password_m
                ports:
                        - "3307:3306"
                volumes:
                        - "./mysql-m.cnf:/etc/mysql/mysql.cnf"
                command:
                        - "--character-set-server=utf8mb4"
                        - "--collation-server=utf8mb4_unicode_ci"
        slave:
                image: mysql
                environment:
                        MYSQL_ROOT_PASSWORD: password_s
                links:
                        - master:master
                depends_on:
                        - master
                ports:
                        - "3308:3306"
                volumes:
                        - "./mysql-s.cnf:/etc/mysql/mysql.cnf"
                command:
                        - "--character-set-server=utf8mb4"
                        - "--collation-server=utf8mb4_unicode_ci"
        slave2:
                image: mysql
                environment:
                        MYSQL_ROOT_PASSWORD: password_s
                links:
                        - master:master
                depends_on:
                        - master
                ports:
                        - "3309:3306"
                volumes:
                        - "./mysql-s2.cnf:/etc/mysql/mysql.cnf"
                command:
                        - "--character-set-server=utf8mb4"
                        - "--collation-server=utf8mb4_unicode_ci"

        php:
                image: tu6ge/php-mysql-backup
                links:
                        - master:master
                        - slave:slave
                        - slave2:salve2
                depends_on:
                        - master
                        - slave 
                        - slave2
                volumes:
                        - "./php/mysql.php:/var/www/html/mysql.php" 
                environment:
                        MASTER_DB_LINK: "mysql://root:password_m@master"
                        SLAVE_DB_LINKS: "mysql://root:password_s@slave|mysql://root:password_s@slave2"
